spring:
  profiles:
    active: dev

---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.czf.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      # 单机默认：defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改 eureka上的默认描述信息
    prefer-ip-address: true  # true，可以显示服务的IP地址

#info配置
info:
  app.name: czf-springcloud
  company.name: com.czf.springcloudstudy

---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.czf.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      # 单机默认：defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改 eureka上的默认描述信息
    prefer-ip-address: true  # true，可以显示服务的IP地址

#info配置
info:
  app.name: czf-springcloud
  company.name: com.czf.springcloudstudy









